# Numpy

In [1]:
import numpy as np

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [5]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [6]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [148]:
np.full((100),3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 5. Поменять 2 строки в матрице

In [24]:
a = np.eye(5)
a[[1,2]] = a[[2,1]]
a

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 6. Создать вектор со значениями от 10 до 100

In [156]:
b = np.arange(10,101,1)
b

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [30]:
np.flip(b)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [36]:
matrix = np.arange(16)
matrix.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [96]:
vec = np.arange(1,6)
vec = vec.reshape(5,-1)
vec = np.insert(vec, [1], [0,0,0], 1)
vec.flatten()

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

#### 10. Создать 3x3 единичную матрицу

In [98]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [100]:
np.random.random((3,3,3))

array([[[0.77531952, 0.52264376, 0.82344252],
        [0.54129873, 0.56994848, 0.17716048],
        [0.21330919, 0.30762191, 0.07943451]],

       [[0.2659963 , 0.9114522 , 0.65310288],
        [0.15806408, 0.29874842, 0.77351394],
        [0.29844849, 0.80623233, 0.01009225]],

       [[0.63322701, 0.85416002, 0.20275958],
        [0.14379795, 0.55113331, 0.3210756 ],
        [0.39819863, 0.89584947, 0.05067697]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [105]:
arr1 = np.random.random((10,10,10))
print(arr1.min())
print(arr1.max())

0.002593614642699027
0.9999670633697816


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [113]:
np.random.random(30).mean()

0.5162579443163258

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [131]:
matrix1 = np.zeros((10,12))
matrix1[:, [0, len(matrix1[0]) -1 ]] = 1
matrix1[[0, len(matrix1) - 1], :] = 1
matrix1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [145]:
a1 = 2 * np.ones(64)
a1 = a1.reshape(-1,8)
a2 = np.ones(32)
a2 = a2.reshape(8, -1)
a1 @ a2

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [186]:
matrix2 = np.zeros((5,5))
np.fill_diagonal(matrix2[1:, :-1],[1,2,2,4])
matrix2


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [188]:
matrix3 = np.zeros((8,8))
matrix3[::2, ::2] = 1
matrix3[1::2, 1::2] = 1
matrix3        

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [192]:
np.where(matrix3 == matrix3.ravel()[11])

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7]),
 array([0, 2, 4, 6, 1, 3, 5, 7, 0, 2, 4, 6, 1, 3, 5, 7, 0, 2, 4, 6, 1, 3,
        5, 7, 0, 2, 4, 6, 1, 3, 5, 7]))

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [197]:
np.tile([[1,0],[0,1]],(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [198]:
a1 @ a2 

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [205]:
arr2 = np.arange(0,10)
arr2[(arr2 > 3) & (arr2 < 8)] *= -1
arr2

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [208]:
arr3 = [[0,1,3,4,5]]
np.repeat(arr3,5,0)

array([[0, 1, 3, 4, 5],
       [0, 1, 3, 4, 5],
       [0, 1, 3, 4, 5],
       [0, 1, 3, 4, 5],
       [0, 1, 3, 4, 5]])

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [209]:
np.random.random(10)

array([0.18209364, 0.08352214, 0.63018756, 0.88575519, 0.24415716,
       0.87381417, 0.73931372, 0.28905514, 0.70092394, 0.09948793])

#### 26. Отсортировать вектор

In [215]:
np.random.random(10).sort()

#### 27. Проверить, одинаковы ли 2 numpy массива

In [217]:
np.array_equal(arr1, arr2)

True

#### 28. Сделать массив неизменяемым

In [240]:
np.zeros(10).flags.writeable = True 

#### 29. Найти n наибольших значений в массиве

In [230]:
arr4 = np.random.random(100)
arr4.sort()
np.flip(arr4)[:10]

array([0.99288895, 0.98728287, 0.9774937 , 0.96987652, 0.9627632 ,
       0.95438203, 0.95175894, 0.93863617, 0.93777695, 0.93082001])

#### 30. Заменить максимальный элемент на ноль

In [237]:
arr4[np.argmax(arr4)] = 0

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [246]:
1.0 / np.subtract.outer(np.arange(1,10) * 2 + 2, np.arange(1,10))

/Users/daniilvdovinov/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.33333333,  0.5       ,  1.        ,         inf, -1.        ,
        -0.5       , -0.33333333, -0.25      , -0.2       ],
       [ 0.2       ,  0.25      ,  0.33333333,  0.5       ,  1.        ,
                inf, -1.        , -0.5       , -0.33333333],
       [ 0.14285714,  0.16666667,  0.2       ,  0.25      ,  0.33333333,
         0.5       ,  1.        ,         inf, -1.        ],
       [ 0.11111111,  0.125     ,  0.14285714,  0.16666667,  0.2       ,
         0.25      ,  0.33333333,  0.5       ,  1.        ],
       [ 0.09090909,  0.1       ,  0.11111111,  0.125     ,  0.14285714,
         0.16666667,  0.2       ,  0.25      ,  0.33333333],
       [ 0.07692308,  0.08333333,  0.09090909,  0.1       ,  0.11111111,
         0.125     ,  0.14285714,  0.16666667,  0.2       ],
       [ 0.06666667,  0.07142857,  0.07692308,  0.08333333,  0.09090909,
         0.1       ,  0.11111111,  0.125     ,  0.14285714],
       [ 0.05882353,  0.0625    ,  0.06666667,  0.07142857,  0

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [248]:
np.iinfo(np.int8).max
np.iinfo(np.int8).min

-128

#### 34. Напечатать все значения в массиве

In [255]:
np.set_printoptions(threshold=np.maximum)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

In [256]:
arr4 = arr4.astype(np.float32, copy=False)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [258]:
for a,b in np.ndenumerate(arr2):
    print(a,b)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) -4
(5,) -5
(6,) -6
(7,) -7
(8,) 8
(9,) 9


#### 38. Случайно расположить p элементов в 2D массив

In [264]:
np.put(np.zeros((10,10)), np.random.choice(range(10*10), 5, replace=False), 1)

#### 39. Отнять среднее из каждой строки в матрице

In [266]:
A = np.random.rand(5, 3)
A - A.mean(axis=1, keepdims=True)

array([[-0.17294187, -0.0520165 ,  0.22495838],
       [-0.01951307, -0.0735449 ,  0.09305797],
       [ 0.13504838,  0.01788315, -0.15293153],
       [ 0.00669872, -0.04087167,  0.03417296],
       [ 0.05898826, -0.41780364,  0.35881538]])

#### 40. Отсортировать матрицу по n-ому столбцу

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [269]:
A = np.random.randint(0,3,(10,10))
print((~A.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [271]:
A = np.random.randint(0,10, (3,4,3,4))
A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

array([[41, 69, 38, 38],
       [42, 80, 57, 52],
       [56, 61, 62, 45]])